name: thesis
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2022.4.26
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - console_shortcut=0.1.1
  - cryptography=38.0.4
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=12.0.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.0.140
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.0.146
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.0.146
  - cuda-runtime=11.6.1
  - cuda-sanitizer-api=12.0.140
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cudatoolkit=11.3.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.3.7
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - flatbuffers=2.0.0
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - future=0.18.2
  - gast=0.4.0
  - getopt-win32=0.1
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpcio=1.42.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gts=0.7.6
  - h5py=3.7.0
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcurand=10.3.1.124
  - libcurand-dev=10.3.1.124
  - libcurl=7.87.0
  - libcusolver=11.3.4.124
  - libcusolver-dev=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.8
  - libffi=3.4.2
  - libgd=2.3.3
  - libiconv=1.16
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libogg=1.3.5
  - libopencv=4.6.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - ninja-base=1.10.2
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nsight-compute=2022.4.1.6
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.1
  - opencv=4.6.0
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=22.0
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pip=22.3.1
  - pixman=0.40.0
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py-opencv=4.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydot=1.4.2
  - pydotplus=2.0.2
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywin32=305
  - pywinpty=2.0.2
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.14.1
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - bagpy==0.5
      - bitstring==4.0.1
      - boto3==1.26.54
      - botocore==1.29.54
      - catkin-pkg==0.5.2
      - cchardet==2.1.7
      - chardet==5.1.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - deeplake==3.2.3
      - dill==0.3.6
      - distro==1.8.0
      - docutils==0.19
      - exceptiongroup==1.1.0
      - fastprogress==1.0.3
      - filelock==3.10.6
      - fire==0.5.0
      - flask==2.2.2
      - fonttools==4.38.0
      - gnupg==2.3.1
      - hub==3.0.1
      - huggingface-hub==0.13.3
      - humbug==0.2.7
      - imageio-ffmpeg==0.4.3
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - itsdangerous==2.1.2
      - jieba==0.42.1
      - jinja2==3.0.3
      - jmespath==1.0.1
      - joblib==1.2.0
      - keras-bert==0.89.0
      - keras-embed-sim==0.10.0
      - keras-layer-normalization==0.16.0
      - keras-multi-head==0.29.0
      - keras-pos-embd==0.13.0
      - keras-position-wise-feed-forward==0.8.0
      - keras-self-attention==0.51.0
      - keras-transformer==0.40.0
      - kiwisolver==1.4.4
      - ktrain==0.33.4
      - langdetect==1.0.9
      - libclang==15.0.6.1
      - matplotlib==3.6.3
      - multiprocess==0.70.14
      - ninja==1.11.1
      - numcodecs==0.11.0
      - opencv-python==4.7.0.72
      - pandas==1.5.3
      - pathos==0.3.0
      - pillow==9.4.0
      - plotly==5.13.0
      - pluggy==1.0.0
      - pox==0.3.2
      - ppft==1.7.6.6
      - protobuf==3.19.6
      - py3rosmsgs==1.18.2
      - pycryptodomex==3.17
      - pyparsing==3.0.9
      - pyserial==3.5
      - pyspng==0.1.1
      - pytest==7.2.1
      - python-graphviz==0.20.1
      - python-version==0.0.2
      - pytorch-ranger==0.1.1
      - regex==2023.3.23
      - rospkg==1.4.0
      - s3transfer==0.6.0
      - scikit-learn==1.2.1
      - seaborn==0.12.2
      - sentencepiece==0.1.97
      - setuptools-scm==7.1.0
      - sklearn==0.0.post1
      - syntok==1.4.4
      - tenacity==8.1.0
      - tensorflow-addons==0.14.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - torch-optimizer==0.3.0
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.64.1
      - transformers==4.27.3
      - typeguard==2.13.3
      - whoosh==2.7.4
